import re

def clean_ai_response(text: str) -> str:
    if not text:
        return ""
    # Remove text: or speech: prefixes often generated by some models
    cleaned = re.sub(r'^(text|speech):\s*\[?', '', text, flags=re.IGNORECASE)
    cleaned = re.sub(r'\]$', '', cleaned)
    return cleaned.strip()
