import re

class ServiceOverloadedException(Exception):
    def __init__(self, provider: str, message: str = None):
        self.provider = provider or "AI"
        self.message = message or f"Our {self.provider} service is currently busy. Please try again in a moment."
        super().__init__(self.message)

def clean_ai_response(text: str) -> str:
    if not text:
        return ""
    # Remove text: or speech: prefixes often generated by some models
    cleaned = re.sub(r'^(text|speech):\s*\[?', '', text, flags=re.IGNORECASE)
    cleaned = re.sub(r'\]$', '', cleaned)
    return cleaned.strip()
